services:
  - type: web
    name: moneymanager-api
    env: node
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Le altre variabili d'ambiente le aggiungerai manualmente nel dashboard Render
    # per maggiore sicurezza (CONNECTION_STRING, JWT_SECRET, etc.)
